//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.Repository.Entity.MetaData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTitle
    {
        public ProductTitle()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int ProductTitleId { get; set; }
        public string ProductName { get; set; }
        public int ColorId { get; set; }
        public int BrandId { get; set; }
        public int CategoryId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
